=== TenzinYangzom158/Programs/EmployeeManagement.xsd
<?xml version="1.0" encoding="UTF-8"?>
<emp:schema xmlns:emp="http://www.w3.org/2001/XMLSchema">

<emp:element name="Company">
<emp:complexType>
<emp:sequence>
<emp:element name="Employee" maxOccurs="unbounded">
	<emp:complexType>
	<emp:sequence>
	<emp:element name="Emp_id" type="emp:integer"></emp:element>
	<emp:element name="Emp_name" type="emp:string"></emp:element>
	<emp:element name="Emp_age" type="emp:integer"></emp:element>
	<emp:element name="Emp_salary" type="Salary"></emp:element>
	<emp:element name="Emp_emailid" type="Email"></emp:element>
	<emp:element name="Emp_Phonenum" type="Phone"></emp:element>
	<emp:element name="Emp_designation" type="emp:string"></emp:element>
	</emp:sequence>
	<emp:attribute name="id" type="emp:int"></emp:attribute>
	</emp:complexType>
</emp:element>
</emp:sequence>
</emp:complexType>

<emp:unique name="EmpIdUniqueKey">
        <emp:selector xpath="Employee" />
        <emp:field xpath="@Emp_id" />
</emp:unique>

</emp:element>

<emp:simpleType name="Salary">
<emp:restriction base="emp:integer">
<emp:minInclusive value="50000"></emp:minInclusive>
<emp:maxInclusive value="200000"></emp:maxInclusive>
</emp:restriction>
</emp:simpleType>

<emp:simpleType name="Phone">
<emp:restriction base="emp:integer">
<emp:pattern value="([0-9]{10})"></emp:pattern>
</emp:restriction>
</emp:simpleType>

<emp:simpleType name="Email">
<emp:restriction base="emp:string">
<emp:pattern value="[^@]+@[^\.]+\..+"></emp:pattern>
</emp:restriction>
</emp:simpleType>


</emp:schema>

=== TenzinYangzom158/Programs/EmployeeManagement.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EmpStyle.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="EmployeeManagement.xsd">

  <Employee id="1">
  
	<Emp_id>1</Emp_id>
    <Emp_name>Tenzin</Emp_name>
    <Emp_age>22</Emp_age>
    <Emp_salary>60000</Emp_salary>
    <Emp_emailid>tenzin@gmail.com</Emp_emailid>
    <Emp_Phonenum>8786756456</Emp_Phonenum>
    <Emp_designation>Developer</Emp_designation>
  </Employee>
  <Employee id="2">
    <Emp_id>2</Emp_id>
    <Emp_name>Yangzom</Emp_name>
    <Emp_age>40</Emp_age>
    <Emp_salary>70000</Emp_salary>
    <Emp_emailid>yangzom@gmail.com</Emp_emailid>
    <Emp_Phonenum>8786756456</Emp_Phonenum>
    <Emp_designation>Test Lead</Emp_designation>
  </Employee>
  <Employee id="3">
    <Emp_id>3</Emp_id>
    <Emp_name>Yeshi</Emp_name>
    <Emp_age>56</Emp_age>
    <Emp_salary>120000</Emp_salary>
    <Emp_emailid>yeshi@gmail.com</Emp_emailid>
    <Emp_Phonenum>8786745664</Emp_Phonenum>
    <Emp_designation>Design Engineer</Emp_designation>
  </Employee>
  <Employee id="4">
    <Emp_id>4</Emp_id>
    <Emp_name>Nyima</Emp_name>
    <Emp_age>32</Emp_age>
    <Emp_salary>51000</Emp_salary>
    <Emp_emailid>nyima@gmail.com</Emp_emailid>
    <Emp_Phonenum>8783676456</Emp_Phonenum>
    <Emp_designation>HR</Emp_designation>
  </Employee>
</Company>
